acts-project/covfie

- .github/workflows/builds.yml
- CMakeLists.txt
- benchmarks/CMakeLists.txt
- benchmarks/cuda/CMakeLists.txt
- cmake/covfie-compiler-options-cpp.cmake
- cmake/covfie-compiler-options-cuda.cmake
- cmake/covfie-functions.cmake
- examples/CMakeLists.txt
- examples/cuda/CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
- tests/CMakeLists.txt
- tests/cuda/CMakeLists.txt
Removed the hardcoded compiler flags from the `covfie::core` and `covfie::cuda` libraries, and replaced them with the same sort of "directory scope" flag settings that we use in the other R&D projects as well.
This is needed as input for making Detray functional on Windows. :wink: But in general, this should be a healthy update for the project's configuration.
> Compiler Flag Cleanup, main branch (2023.10.09.)

- lib/core/covfie/core/backend/transformer/backup.hpp
- lib/core/covfie/core/backend/transformer/clamp.hpp
- lib/core/covfie/core/backend/transformer/hilbert.hpp
- lib/core/covfie/core/backend/transformer/linear.hpp
These haven't been used in a while and they have fallen behind as the rest of the library has progressed. This commit pulls them up to speed with recent developments.
> Fix some old and neglected storage backends

- tests/core/CMakeLists.txt
- tests/core/test_build.cpp
This commit adds some explicit template instantiations to ensure that concepts hold and that things can be compiled succesfully.
> Add additional core library build tests

- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_texture.hpp
- lib/cuda/covfie/cuda/utility/memory.hpp
The CUDA compiler now supports C++20 concepts, which has exposed some errors in the CUDA backends. This commit repairs the relevant backends so they comply with the necessary concepts and can be compiled accordingly.
> Update CUDA backends to meet concepts

- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
The CPU and CUDA libraries were previously not being linked against the core library which they should be. This commit resolves that problem.
> Add missing CMake interface libraries

- lib/core/covfie/core/backend/transformer/dereference.hpp
- lib/core/covfie/core/backend/transformer/hilbert.hpp
- lib/core/covfie/core/backend/transformer/linear.hpp
- lib/core/covfie/core/backend/transformer/nearest_neighbour.hpp
- lib/core/covfie/core/backend/transformer/shuffle.hpp
- lib/core/covfie/core/parameter_pack.hpp
- lib/core/covfie/core/utility/nd_map.hpp
- lib/cuda/covfie/cuda/error_check.hpp
This commit ensures that the headers in the core, CPU, and CUDA plugins can be compiled stand-alone, preventing nasty surprises for users.
> Make public headers work standalone

- .github/workflows/builds.yml
This commit enables support for building and testing the project on Windows CI runners.
> Add support for Windows tests in the CI

- tests/CMakeLists.txt
- tests/googletest/CMakeLists.txt
- tests/googletest/README.md
This commit adds the ability for the CMake build system to set up GoogleTest from a remote source, and to disable the set-up of GoogleTest entirely.
> Allow CMake to set up the GoogleTest project

- lib/core/covfie/core/backend/transformer/linear.hpp
- lib/core/covfie/core/backend/transformer/nearest_neighbour.hpp
Somehow, making the scalar type in the nearest neighbour and linear interpolators configurable had slipped my mind. This causes potential conversion warnings. In this commit, I add a user-facing configuration parameter which allows the user to set the input scalar type.
> Add configurable input vectors to interpolators

- extra/parameter_pack_gen/gen_parameter_pack_code.py
- lib/core/covfie/core/parameter_pack.hpp
- lib/core/covfie/core/utility/backend_traits.hpp
This commit adds the `make_parameter_pack_for` functions which helps reduce the amount of boilerplate code when configuring vector fields. Unfortunately, this code is auto-generated because of a problem with the C++ language.
> Add `make_parameter_pack_for` utility function

- tests/core/CMakeLists.txt
- tests/core/test_canonical.cpp
Inspired by concerns from @krasznaa, this commit adds tests for the canonical, strided array layout backend transformers.
> Add tests for the canonical layout backends

- README.md
Reading and writing the ATLAS field is one of our primary use cases right now. This commit adds a section to the README on how to do that.
> Add README section on ATLAS field conversion

- lib/core/covfie/core/backend/transformer/dereference.hpp
- lib/core/covfie/core/backend/transformer/linear.hpp
- lib/core/covfie/core/backend/transformer/nearest_neighbour.hpp
- lib/core/covfie/core/backend/transformer/shuffle.hpp
Previously, magic numbers were written to binary files even for backends which don't have any kind of data at all, such as interpolators. Since this cannot lead to data loss, this is overly restrictive. This commit removes those magic numbers to enable more permissive conversion.
> Remove magic headers in config-less backends

- lib/core/covfie/core/utility/backend_traits.hpp
Versions of gcc were incorrectly reporting errors in the `nth_backend` helper function, even though it is (as far as I can tell) correctly defined. This commit adds some failsafes.
> Fix SFINAE bug in gcc 11

- tests/core/CMakeLists.txt
- tests/core/test_atlas_like_io.cpp
This commit adds a test for the convertability of interpolation types at binary IO time, which is a problem faced by @beomki-yeo.
> Add tests for convertibility of interpolators

- examples/core/convert_bfield_csv.cpp
This commit resolves an issues in the CSV-based magnetic field conversion which produced some double-to-float conversion warnings.
> Stop MSVC whining about lossy conversions

- cmake/covfieConfig.cmake.in
As it stands, an installed version of covfie with the CUDA plugin available will correctly try to link against the CUDA runtime in a dependent project, but it won't actually look for it. This means that, if the order of operations happens to be such that covfie is loaded before CUDA, a configuration error will be thrown. This commit ensures that the installed CMake configuration looks for the CUDA runtime.
> Find CUDA dependencies in installed CMake configs

- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
This fixes a concept mismatch, stemming from the time that concepts were not supported in CUDA.
> Add missing constructor to CUDA array

- lib/core/covfie/core/backend/primitive/array.hpp
- lib/core/covfie/core/backend/primitive/constant.hpp
- lib/core/covfie/core/backend/primitive/identity.hpp
- lib/core/covfie/core/backend/transformer/affine.hpp
- lib/core/covfie/core/backend/transformer/backup.hpp
- lib/core/covfie/core/backend/transformer/clamp.hpp
- lib/core/covfie/core/backend/transformer/dereference.hpp
- lib/core/covfie/core/backend/transformer/hilbert.hpp
- lib/core/covfie/core/backend/transformer/linear.hpp
- lib/core/covfie/core/backend/transformer/morton.hpp
- lib/core/covfie/core/backend/transformer/nearest_neighbour.hpp
- lib/core/covfie/core/backend/transformer/shuffle.hpp
- lib/core/covfie/core/backend/transformer/strided.hpp
- lib/core/covfie/core/definitions.hpp
- lib/core/covfie/core/field.hpp
- lib/core/covfie/core/field_view.hpp
- lib/cpu/covfie/cpu/backend/primitive/c_array.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_texture.hpp
This macro is no longer necessary now that we have C++20 enabled as the minimum C++ standard.
> Remove `CONSTRAINT` macro

- lib/core/covfie/core/backend/transformer/covariant_cast.hpp
- tests/core/CMakeLists.txt
- tests/core/test_covariant_cast.cpp
The idea here is to allow the user to convert a $T \to U^n$ backend into a $T \to V^n$ by specifying a target $U \to V$ cast.
> Add covariant casting transformer

- lib/core/covfie/core/backend/transformer/linear.hpp
- tests/core/CMakeLists.txt
- tests/core/test_build.cpp
- tests/core/test_linear_interpolator.cpp
This commit applies major changes to the linear interpolator, fixing bugs, adding requirements and allowing it to work for arbitrarily many dimensions. Also adds tests for it.
> Fix the linear interpolator

- examples/cpu/render_slice.cpp
- examples/cuda/render_slice.cu
- examples/cuda/render_slice_texture.cu
In 695586b, the field conversion executables were updated to use units other than tesla, which broke the rendering executables. This commit makes the rendering executables aware of the change, allowing them to produce nice images again.
> Update render executables to use right unit

- lib/core/covfie/core/backend/transformer/linear.hpp
MSVC doesn't like when you shift an integer of type $A$ with an integer of type $B$, which I guess is fair.
> Fix some MSVC barrel shift warnings

- .github/workflows/builds.yml
Enables parallelism, uses the NVIDIA Docker containers, and removes the Windows CI.
> Redesign the build test CI jobs

- lib/core/covfie/core/backend/primitive/array.hpp
- lib/core/covfie/core/backend/transformer/hilbert.hpp
- lib/core/covfie/core/backend/transformer/morton.hpp
- lib/core/covfie/core/backend/transformer/strided.hpp
Especially the low-level ones and the layout ones can benefit from having asserts to assure we don't go out of bounds.
> Add bounds assertions to several backends

- .pre-commit-config.yaml
- CMakeLists.txt
- benchmarks/CMakeLists.txt
- benchmarks/cuda/CMakeLists.txt
- ci/check_license.py
- cmake/covfie-compiler-options-cpp.cmake
- cmake/covfie-compiler-options-cuda.cmake
- cmake/covfie-functions.cmake
- examples/CMakeLists.txt
- examples/cuda/CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
- tests/CMakeLists.txt
- tests/cuda/CMakeLists.txt
- tests/googletest/CMakeLists.txt
This commit extends the enforcement of license headers to include CMake files, as well as the existing C++ files.
> Harmonize license header in CMake files

- CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
We previously relied on `CMAKE_INSTALL_INCLUDEDIR` being set, but this is not guaranteed unless `GNUInstallDirs`. CMake, of course, was quietly swallowing this code and producing invalid installations. This commit ensures that `GNUInstallDirs` is always loaded before the install interfaces are defined, and also uses the `CMAKE_INSTALL_INCLUDEDIR` variable more consistently.
> Fix bug in the CMake install interface

- .github/workflows/downstream.yml
- tests/downstream/CMakeLists.txt
- tests/downstream/main.cpp
This commit adds a new CI job that tests whether covfie can be used as a dependency in a downstream project.
> Add tests for downstream builds

- benchmarks/common/CMakeLists.txt
- benchmarks/cpu/CMakeLists.txt
- benchmarks/cuda/CMakeLists.txt
- benchmarks/openmp/CMakeLists.txt
- examples/core/CMakeLists.txt
- examples/cpu/CMakeLists.txt
- examples/cuda/CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
- tests/core/CMakeLists.txt
- tests/cpu/CMakeLists.txt
- tests/cuda/CMakeLists.txt
This is to avoid name collisions with other libraries when used as a downstream project.
> Add `covfie_` prefix to library targets

- examples/common/bitmap/bitmap.cpp
- examples/common/bitmap/bitmap.hpp
- examples/cpu/render_image.cpp
- examples/cpu/render_slice.cpp
- examples/cuda/render_slice.cu
- examples/cuda/render_slice_texture.cu
This ensures that the rendered bitmaps don't come out weirdly on platforms where chars are singed by default.
> Use unsigned chars for image rendering

- CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
I recently noticed that covfie tries to install itself even if it is not the top level project, which is obviously problematic. This commit fixes this behaviour, adding install rules only if the project is top level.
> Enable installation only if top-level

- CMakeLists.txt
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
This reverts commit aef0d2eeb75d536300b0fdb99d75bedbdb45238f, as it breaks CMake's silly install logic.
> Revert "Enable installation only if top-level"

- CMakeLists.txt
- cmake/covfie-functions.cmake
- lib/core/CMakeLists.txt
- lib/cpu/CMakeLists.txt
- lib/cuda/CMakeLists.txt
This code adds a lot of complexity to our CMake configuration but primarily requires us to know about the CUDA runtime in the main library, which I want to get rid of.
> Remove header testing code

- README.md
- spack.yaml
This commit adds a Spack environment specification for our build-time dependencies.
> Add Spack environment specification

- CMakeLists.txt
- cmake/covfieConfig.cmake.in
- docs/user/installation.rst
- docs/user/integration.rst
- examples/cuda/CMakeLists.txt
- lib/CMakeLists.txt
- lib/cuda/CMakeLists.txt
- tests/cuda/CMakeLists.txt
Currently, the selected platforms determine which header files are installed, but this is not a great design; it makes the installation depend very heavily on the configuration of the project which makes little sense for a header-only library. This commit reworks this design, installing all headers regardless of the configuration. The platform variables now only impact the tests, the examples, and the benchmarks.
> Rework platform selection CMake code

- lib/core/covfie/core/array.hpp
Default functions do not need any host or device qualifiers as they are fully controlled by the compiler.
> Remove device qualifiers from default functions

- CMakeLists.txt
- cmake/covfieConfig.cmake.in
- docs/user/integration.rst
- lib/core/CMakeLists.txt
We now require all C++20 features to be enabled, so the `COVFIE_QUIET` flag is no longer useful.
> Remove quiet setting about C++20 features

- examples/core/asm.cpp
- extra/parameter_pack_gen/gen_parameter_pack_code.py
- lib/core/covfie/core/algebra/vector.hpp
- lib/core/covfie/core/backend/transformer/affine.hpp
- lib/core/covfie/core/backend/transformer/backup.hpp
- lib/core/covfie/core/backend/transformer/clamp.hpp
- lib/core/covfie/core/backend/transformer/hilbert.hpp
- lib/core/covfie/core/backend/transformer/linear.hpp
- lib/core/covfie/core/backend/transformer/morton.hpp
- lib/core/covfie/core/backend/transformer/nearest_neighbour.hpp
- lib/core/covfie/core/backend/transformer/strided.hpp
- lib/core/covfie/core/field_view.hpp
- lib/core/covfie/core/parameter_pack.hpp
- lib/core/covfie/core/utility/numeric.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_texture.hpp
This commit replaces all uses of `std::enable_if` by the much more elegant `requires` keyword.
> Remove all usage of `std::enable_if`

- .gitignore
This commit expands the `.gitignore` file, adding the `.env` and `.cache` directories for Spack and clangd, respectively.
> Expand git ignore list

- lib/core/covfie/core/backend/primitive/array.hpp
- lib/core/covfie/core/concepts.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
This commit allows for the direct conversion of CPU arrays to CUDA arrays, which was previously possible only through some transformer like the strided backend.
> Allow direct conversion of CPU array to CUDA

- tests/cuda/CMakeLists.txt
- tests/cuda/test_cuda_array.cu
- tests/cuda/test_cuda_texture.cu
This commit adds additional tests for the CUDA array and texture backends, which were previously woefully untested.
> Add tests for CUDA array and texture backend

- lib/core/covfie/core/backend/transformer/strided.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
This commit fixes the assignment constructor and operator in the strided array, and fixes the CUDA device array to match this.
> Fix assignment constructor in strided array

- tests/cuda/test_cuda_array.cu
- tests/cuda/test_cuda_strided_array.cu
- tests/cuda/test_cuda_texture.cu
The CUDA tests previously bunched many field types (copied, assigned, etc.) together. This commit splits up the tests so they are easier to debug. Also adds new tests for the strided array.
> Refactor and expand CUDA tests

- lib/cuda/covfie/cuda/backend/primitive/cuda_texture.hpp
This commit fixes a small bug in which the array pointer in the CUDA texture backend was not properly nulled, sometimes leading to memory errors.
> Explicitly set CUDA texture array pointer to null

- lib/cuda/covfie/cuda/backend/primitive/cuda_device_array.hpp
- lib/cuda/covfie/cuda/backend/primitive/cuda_texture.hpp
- lib/cuda/covfie/cuda/utility/copy.hpp
- lib/cuda/covfie/cuda/utility/memory.hpp
- tests/cuda/test_cuda_array.cu
- tests/cuda/test_cuda_strided_array.cu
- tests/cuda/test_cuda_texture.cu
This commit adds support for constructing CUDA backends on streams. While this remains fully synchronous for now, this will later allow for the use of asynchronous code and it also provides a template of how to implement SYCL code.
> Implement support for CUDA streams

- .github/workflows/builds.yml
- CMakeLists.txt
- lib/CMakeLists.txt
- lib/core/covfie/core/concepts.hpp
- lib/sycl/CMakeLists.txt
- lib/sycl/covfie/sycl/backend/primitive/sycl_device_array.hpp
- lib/sycl/covfie/sycl/utility/copy.hpp
- lib/sycl/covfie/sycl/utility/memory.hpp
- lib/sycl/covfie/sycl/utility/unique_ptr.hpp
- tests/CMakeLists.txt
- tests/sycl/CMakeLists.txt
- tests/sycl/retrieve_vector.hpp
- tests/sycl/test_sycl_array.cpp
This commit adds support for SYCL arrays, allowing us to use covfie to represent magnetic fields on Intel GPUs and other devices.
> Add support for SYCL arrays

- lib/cuda/CMakeLists.txt
- lib/hip/CMakeLists.txt
Downstream projects that use a public interface less than C++20 require the CUDA compiler to be informed explicitly about the standard required for the CUDA code. The same is true for HIP.
> Add HIP/CUDA standards to libraries

- CMakeLists.txt
Calling the `project` function in CMake will, by default, enable both the C and C++ languages. Since we don't use C, this commit explicitly turns that off.
> Explicitly disable the C language

- lib/core/covfie/core/algebra/matrix.hpp
Fix a warning by explicitly declaring the copy-assignment operator:
```c++
lib/core/covfie/core/algebra/matrix.hpp:34:5: warning: definition of implicit copy assignment operator for 'matrix<3, 4>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
34 |     matrix(const matrix<N, M, T, I> &) = default;
```
> Explicitly declare matrix copy assignment

- CONTRIBUTING.md
- REUSE.toml
This commit adds a short document with best practices and tips for first-time contributors.
Closes #79.
> Add contribution guidelines

- .gersemirc
- CMakeLists.txt
- LICENSES/Apache-2.0.txt
- REUSE.toml
- cmake/.gitattributes
- cmake/CgvFindVersion.cmake
- cmake/covfieConfig.cmake.in
Even though the latest version of Covfie was released through git as v0.13, **the CMake metadata remains at 0.12.1** (and thus the version reported from a spack install is wrong) .  I have added https://github.com/sethrj/cmake-git-version which
Issues for this PR because it won't lint:
- I'm not sure if/how the license of this product should be updated in the REUSE
- REUSE lint also complains a bout missing license in .gitattributes (really?)
- CMake lint complains about missing functions, which there aren't (so I may be misunderstanding it)
- Is there a way to exclude the CMake file from formatting, so it can be diffed against the main version upstream?
> Add CMakeGitVersion to auto-fill covfie_VERSION from git metadata

- lib/core/covfie/core/backend/primitive/array.hpp
While reworking covfie usage in Celeritas to no longer use `unique_ptr`, I found that the copy assignment of  `owning_data_t` was missing a return value.
> Fix `owning_data_t` copy assignment

- lib/sycl/covfie/sycl/backend/primitive/sycl_device_array.hpp
Removed erroneous host based copy for SYCL device memory. Which lead to issues as soon as using a SYCL device that would have its own device memory.
I tested with [traccc](https://github.com/acts-project/traccc) that things seem to work fine without this `std::memcpy` present. Since the memory is already copied correctly in lines 70-72.
> Remove erroneous memory copy from SYCL array

- lib/core/covfie/core/backend/transformer/clamp.hpp
The clamp backend, when constructed over a natural-number-delimited underlying field, previously assumed the clamp limit to be off by one. Indeed, `clamp(a, n, b)` can return `b` inclusively. It was previously assumed that this was exclusive. Subtracting one from the clamp parameters fixes this issue.
> Fix off-by-one error in clamp backend
